### PR TITLE
fix(iframe-resizer) actually resize things. closes #71

### LINKED ISSUE #71: iframe-resizer doesn't do anything at all, whatsoever, other than take up space
It needs something happening in the client.

@rschick

### PR DESCRIPTION
**Pull request by omsmith**

### CODE REVIEW

File: src/client.js [hunk 1]
```diff
@@ -4,6 +4,7 @@ var inherits = require('inherits'),
 	Promise = require('lie');
 
 var Port = require('./port'),
+	resizer = require('./plugins/iframe-resizer/client'),
```
Comment (omsmith) [inline src/client.js]: I would rather this not be brought in by the client by default, but that's a change I'll make on the client/host at the same time, later (that's step 3)

**Comment by omsmith** [comment]
I assume this works

File: src/plugins/iframe-resizer/client.js [hunk 2]
```diff
@@ -0,0 +1,9 @@
+'use strict';
+
+module.exports = function(client) {
+	window.iframeResizer = {
+		targetOrigin: client._targetOrigin
+	};
+
+	require('iframe-resizer/js/iframeResizer.contentWindow');
```
Comment (omsmith) [inline src/plugins/iframe-resizer/client.js]: This executes immediately, which is why the `require` is nested within the plugin usage

File: README.md [hunk 3]
```diff
@@ -81,6 +81,7 @@ Parameters:
 
 * `options`
  * `debug`: whether to enable console debugging, `false` by default
+ * `resizeFrame`: whether this `Client` should participate in automatic resizing. `true` by default
```
Comment (omsmith) [inline README.md]: I'll call this _semver-minor_
